# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 16:46
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAuditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, verbose_name='Логин пользователя')),
                ('userid', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Идентификатор пользователя')),
                ('user_fio', models.CharField(blank=True, db_index=True, default='', max_length=70, null=True, verbose_name='ФИО пользователя')),
                ('user_info', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Дополнительные сведения о пользователе')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Вход в систему'), (1, 'Выход из системы')], db_index=True, verbose_name='Действие')),
            ],
            options={
                'db_table': 'm3_audit_auth',
                'verbose_name': 'Авторизации пользователей',
            },
        ),
        migrations.CreateModel(
            name='DefaultModelChangeAuditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, verbose_name='Логин пользователя')),
                ('userid', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Идентификатор пользователя')),
                ('user_fio', models.CharField(blank=True, db_index=True, default='', max_length=70, null=True, verbose_name='ФИО пользователя')),
                ('user_info', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Дополнительные сведения о пользователе')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('object_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ID записи')),
                ('object_model', models.CharField(db_index=True, max_length=300, verbose_name='Модель')),
                ('object_data', models.TextField(verbose_name='Данные модели')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Добавление'), (1, 'Изменение'), (2, 'Удаление')], db_index=True, verbose_name='Действие')),
            ],
            options={
                'db_table': 'm3_audit_model_changes',
                'verbose_name': 'Изменения таблиц системы',
            },
        ),
        migrations.CreateModel(
            name='DictChangesAuditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, verbose_name='Логин пользователя')),
                ('userid', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Идентификатор пользователя')),
                ('user_fio', models.CharField(blank=True, db_index=True, default='', max_length=70, null=True, verbose_name='ФИО пользователя')),
                ('user_info', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Дополнительные сведения о пользователе')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('object_id', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ID записи')),
                ('object_model', models.CharField(db_index=True, max_length=300, verbose_name='Модель')),
                ('object_data', models.TextField(verbose_name='Данные модели')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Добавление'), (1, 'Изменение'), (2, 'Удаление')], db_index=True, verbose_name='Действие')),
            ],
            options={
                'db_table': 'm3_audit_dict_changes',
                'verbose_name': 'Изменения в справочниках',
            },
        ),
        migrations.CreateModel(
            name='RolesAuditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, verbose_name='Логин пользователя')),
                ('userid', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Идентификатор пользователя')),
                ('user_fio', models.CharField(blank=True, db_index=True, default='', max_length=70, null=True, verbose_name='ФИО пользователя')),
                ('user_info', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Дополнительные сведения о пользователе')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Добавление прав'), (1, 'Лишение прав'), (2, 'Активация права'), (3, 'Отключение права')], verbose_name='Действие')),
                ('role_id', models.PositiveIntegerField(verbose_name='ID роли')),
                ('role_name', models.CharField(max_length=200, verbose_name='Роль')),
                ('permission_code', models.CharField(blank=True, default=b'', max_length=200, null=True, verbose_name='Разрешения')),
            ],
            options={
                'db_table': 'm3_audit_roles',
                'verbose_name': 'Изменения ролей пользователей',
            },
        ),
    ]
